config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'
  #mount Attachinary::Engine => "/attachinary"
  resources :cocktails, only: [:show, :index, :new, :create] do
    resources :doses, only: [:create]
  end

  resources :doses, only: [:destroy]

  resources :ingredients, only: [:show]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true, uniqueness: true

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses, dependent: :restrict_with_exception

  validates :name, presence: true

  default_scope -> { order(name: :ASC) }
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  #has_attachments :photos, maximum: 2
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    Cloudinary::Uploader.upload(cocktail_params[:photo])
    if @cocktail.save
      redirect_to @cocktail
    else
      render 'new'
end
    end

  def edit
    @cocktail = Cocktail.find(params[:id])
end

  def update
    @cocktail.update(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private



  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
before_action :set_dose, only: [:destroy]
before_action :dose_params, only: [:new, :create, :destroy]

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @ingredients = Ingredient.all
      render 'cocktails/show'
    end
  end

  def edit
    @cocktail = @dose.cocktail
  end

  def update
    if @dose.update(dose_params)
      redirect_to @dose.cocktail
    else
      render :edit
    end
  end

  def destroy
   @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_dose
    @cocktail = Cocktail.find [:cocktail_id]
  end

  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
    @ingredient = Ingredient.find(params[:id])
    @cocktails = @ingredient.cocktails
  end

  def update
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
    params.require(:product).permit(:name, :description, :photos)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yield_with_default(holder, default)
    if content_for?(holder)
      content_for(holder).squish
    else
      default
    end
  end

  def bootstrap_class_for(flash_type)
    case flash_type
    when :alert   then "alert-error"
    when :notice  then "alert-success"
    end
  end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/cocktails/_form_picture.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :photo %>
  <%= f.button :submit, "Upload" %>
<% end %>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Edit cocktail</h1>
<%= render 'form_picture' %>

app/views/cocktails/index.html.erb
<h1 class="text-center">Les Cocktails</h1>

<html>
  <head>
    <meta charset="utf-8">
    <title>Trend Chart (Area + Line)</title>
    <link rel="stylesheet" href="app.css">
  </head>

  <body>
  </body>

  <script src="http://d3js.org/d3.v3.js"></script>
  <script src="app.js"></script>
</html>

<div class="text-center padded">
  <%= link_to "Create a cocktail", new_cocktail_path, class: "btn btn-primary" %>
</div>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card text-center">

          <% if cocktail.photo %>
            <div class="card" style="background-image: url('<%= image_path cocktail.photo%>')">
            </div>
          <% else %>
            <div class="card" style="background-image: url('http://www.seriouseats.com/images/2014/11/20141104-cocktail-party-old-fashioneds-holiday-vicky-wasik-3.jpg')">
            </div>
          <% end %>
          <div class="card-body">
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Create a new cocktail</h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
  <%= render 'form_picture' %>
<% end %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <h1><%= @cocktail.name %></h1>

      <ul class="list-unstyled">
        <% @cocktail.doses.each do |dose| %>
          <li><%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %> : <%= dose.description %>
              <%= link_to "<i class='fa fa-close'></i>".html_safe, dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>
          </li>
        <% end %>
      </ul>

  <%= simple_form_for([@cocktail, @dose]) do |f| %>
      <br>
      <% if @dose.errors.any? %>
        <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
        <%= f.input :description %>
        <%= f.input :ingredient_id, collection: Ingredient.all, prompt:"choisir ingredient!" %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
      <%= link_to 'Back', @cocktails %>
    </div>
  </div>
  <div class="form">
    <p>📸 upload la photo </p>
    <%= render 'form_picture' %>
</div>
  <div class="picture-list">
    <p>This is how it should look like</p>
    <% if @cocktail.photo? %>
      <% @cocktail.photo.each do |photo| %>
        <%= cl_image_tag photo.path, width: 200, height: 300, crop: :fill %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, collection: Ingredient.all.order(:name), include_blank: false %>
  <%= f.input :description %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/doses/create.html.erb
<div class="container">
  <h1>Your dose has been successfuly added 🎉</h1>
  <p><%= link_to "Back to " + @cocktail.name, cocktail_path(@cocktail)  %></p>
</div>

app/views/doses/destroy.html.erb
<div class="container">
  <h1>Your dose has been successfuly deleted 🎉</h1>
  <p><%= link_to "Back to " + @cocktail.name, cocktail_path(@cocktail)  %></p>
</div>

app/views/doses/edit.html.erb
<h1>Edit Ingredient</h1>
<%= render 'form' %>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<div class="container">
  <h1>Let's add a dose to your cocktail</h1>
  <%= render 'form_dose' %>
</div>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

app/views/ingredients/new.html.erb
<%= simple_form_for [@cocktail, @ingredient] do |f| %>
  <%= f.input :name %>
  <%= f.submit "add a ingredient", class: "btn btn-primary" %>
<% end %>

app/views/ingredients/show.html.erb
<h1>Les cocktails avec <%= @ingredient.name %> sont :</h1>
<ul>
  <% @ingredient.cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
  <% end %>
</ul>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/layouts/_footer.html.erb
<div id="footer">
      <ul class="list-inline">
        <li><a href=""><i class="fa fa-youtube"></i></a></li>
        <li><a href=""><i class="fa fa-instagram"></i></a></li>
        <li><a href=""><i class="fa fa-facebook"></i></a></li>
        <li><a href=""><i class="fa fa-twitter"></i></a></li>
      </ul>
      <p>This is a Mister Cocktail ! <i class="fa fa-glass" aria-hidden="true"></i></p>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
     <%= form_tag search_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :query, params[:query], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
<% end %>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to "New Cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn btn-medium" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Map</a></li>
        <li><a href="#">Eat</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=raw yield(:title).blank? ? '' : "#{yield(:title)} | " %>Mister Cocktail</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

 <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= cl_image_tag("gcobkfvjq45tjilnw1ek",
      width: 400, height: 300, crop: :fill) %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo, as: :attachinary%>
  <%=# f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
  <%=# image_tag @product.photo.url(:bright_face) %>
</p>


<div class="card"
<% if @product.photo? %>
  <%@product.photos.each do |photo| %> <%= cl_image_tag photo.path, width: 300, height: 200, crop: :fill %> <% end %>
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>
  <a class="card-link" href="#" ></a>
</div>


  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Add a cocktail"), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</div>

app/views/shared/_testimonial.html.erb
<div>
  <%= testimonial.text %>
  <%= testimonial.author.name %>
  <%= image_tag testimonial.author.image %>
</div>